# Generated by Django 3.0.2 on 2020-01-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0002_auto_20200117_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
