# Generated by Django 3.1.1 on 2020-09-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0003_remove_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name='Name')),
                ('l_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytest.post')),
            ],
        ),
    ]
