# Generated by Django 3.1.1 on 2020-09-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0005_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ManyToManyField(to='mytest.Genre'),
        ),
    ]
