# Generated by Django 3.1.1 on 2020-09-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0006_post_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genries'},
        ),
    ]
