# Generated by Django 3.1.1 on 2020-09-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0007_auto_20200927_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
    ]
